// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/jictyvoo/amigonimo_api/internal/domain/authcore/authserv/verify (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=repository_mock_test.go -package=verify github.com/jictyvoo/amigonimo_api/internal/domain/authcore/authserv/verify Repository
//

// Package verify is a generated GoMock package.
package verify

import (
	reflect "reflect"

	entities "github.com/jictyvoo/amigonimo_api/internal/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetUserByVerificationCode mocks base method.
func (m *MockRepository) GetUserByVerificationCode(code string) (entities.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByVerificationCode", code)
	ret0, _ := ret[0].(entities.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByVerificationCode indicates an expected call of GetUserByVerificationCode.
func (mr *MockRepositoryMockRecorder) GetUserByVerificationCode(code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByVerificationCode", reflect.TypeOf((*MockRepository)(nil).GetUserByVerificationCode), code)
}

// SetUserVerified mocks base method.
func (m *MockRepository) SetUserVerified(userID entities.HexID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUserVerified", userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetUserVerified indicates an expected call of SetUserVerified.
func (mr *MockRepositoryMockRecorder) SetUserVerified(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUserVerified", reflect.TypeOf((*MockRepository)(nil).SetUserVerified), userID)
}
