// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/jictyvoo/amigonimo_api/internal/domain/authcore/authserv (interfaces: MailerService)
//
// Generated by this command:
//
//	mockgen -destination=mailer_service_mock_test.go -package=authserv github.com/jictyvoo/amigonimo_api/internal/domain/authcore/authserv MailerService
//

// Package authserv is a generated GoMock package.
package authserv

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMailerService is a mock of MailerService interface.
type MockMailerService struct {
	ctrl     *gomock.Controller
	recorder *MockMailerServiceMockRecorder
	isgomock struct{}
}

// MockMailerServiceMockRecorder is the mock recorder for MockMailerService.
type MockMailerServiceMockRecorder struct {
	mock *MockMailerService
}

// NewMockMailerService creates a new mock instance.
func NewMockMailerService(ctrl *gomock.Controller) *MockMailerService {
	mock := &MockMailerService{ctrl: ctrl}
	mock.recorder = &MockMailerServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMailerService) EXPECT() *MockMailerServiceMockRecorder {
	return m.recorder
}

// SendActivationEmail mocks base method.
func (m *MockMailerService) SendActivationEmail(email, verificationToken string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SendActivationEmail", email, verificationToken)
}

// SendActivationEmail indicates an expected call of SendActivationEmail.
func (mr *MockMailerServiceMockRecorder) SendActivationEmail(email, verificationToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendActivationEmail", reflect.TypeOf((*MockMailerService)(nil).SendActivationEmail), email, verificationToken)
}

// SendPasswordRecoveryEmail mocks base method.
func (m *MockMailerService) SendPasswordRecoveryEmail(email, recoveryCode string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SendPasswordRecoveryEmail", email, recoveryCode)
}

// SendPasswordRecoveryEmail indicates an expected call of SendPasswordRecoveryEmail.
func (mr *MockMailerServiceMockRecorder) SendPasswordRecoveryEmail(email, recoveryCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendPasswordRecoveryEmail", reflect.TypeOf((*MockMailerService)(nil).SendPasswordRecoveryEmail), email, recoveryCode)
}
