// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/jictyvoo/amigonimo_api/internal/domain/authcore/authserv (interfaces: TokenRepository)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/token_repo_mock.go -package=mocks github.com/jictyvoo/amigonimo_api/internal/domain/authcore/authserv TokenRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	entities "github.com/jictyvoo/amigonimo_api/internal/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockTokenRepository is a mock of TokenRepository interface.
type MockTokenRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTokenRepositoryMockRecorder
	isgomock struct{}
}

// MockTokenRepositoryMockRecorder is the mock recorder for MockTokenRepository.
type MockTokenRepositoryMockRecorder struct {
	mock *MockTokenRepository
}

// NewMockTokenRepository creates a new mock instance.
func NewMockTokenRepository(ctrl *gomock.Controller) *MockTokenRepository {
	mock := &MockTokenRepository{ctrl: ctrl}
	mock.recorder = &MockTokenRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenRepository) EXPECT() *MockTokenRepositoryMockRecorder {
	return m.recorder
}

// CheckAuthenticationByRefreshToken mocks base method.
func (m *MockTokenRepository) CheckAuthenticationByRefreshToken(authToken string) (*entities.AuthenticationToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckAuthenticationByRefreshToken", authToken)
	ret0, _ := ret[0].(*entities.AuthenticationToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckAuthenticationByRefreshToken indicates an expected call of CheckAuthenticationByRefreshToken.
func (mr *MockTokenRepositoryMockRecorder) CheckAuthenticationByRefreshToken(authToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckAuthenticationByRefreshToken", reflect.TypeOf((*MockTokenRepository)(nil).CheckAuthenticationByRefreshToken), authToken)
}

// GetAuthenticationToken mocks base method.
func (m *MockTokenRepository) GetAuthenticationToken(userID entities.HexID) (entities.AuthenticationToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuthenticationToken", userID)
	ret0, _ := ret[0].(entities.AuthenticationToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAuthenticationToken indicates an expected call of GetAuthenticationToken.
func (mr *MockTokenRepositoryMockRecorder) GetAuthenticationToken(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthenticationToken", reflect.TypeOf((*MockTokenRepository)(nil).GetAuthenticationToken), userID)
}

// GetUserByAuthToken mocks base method.
func (m *MockTokenRepository) GetUserByAuthToken(token string) (entities.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByAuthToken", token)
	ret0, _ := ret[0].(entities.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByAuthToken indicates an expected call of GetUserByAuthToken.
func (mr *MockTokenRepositoryMockRecorder) GetUserByAuthToken(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByAuthToken", reflect.TypeOf((*MockTokenRepository)(nil).GetUserByAuthToken), token)
}

// UpdateUserAuthToken mocks base method.
func (m *MockTokenRepository) UpdateUserAuthToken(authentication *entities.AuthenticationToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserAuthToken", authentication)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserAuthToken indicates an expected call of UpdateUserAuthToken.
func (mr *MockTokenRepositoryMockRecorder) UpdateUserAuthToken(authentication any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserAuthToken", reflect.TypeOf((*MockTokenRepository)(nil).UpdateUserAuthToken), authentication)
}
