// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/jictyvoo/amigonimo_api/internal/domain/authcore/authserv (interfaces: UserAuthRepository)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/userauth_repo_mock.go -package=mocks github.com/jictyvoo/amigonimo_api/internal/domain/authcore/authserv UserAuthRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	entities "github.com/jictyvoo/amigonimo_api/internal/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockUserAuthRepository is a mock of UserAuthRepository interface.
type MockUserAuthRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserAuthRepositoryMockRecorder
	isgomock struct{}
}

// MockUserAuthRepositoryMockRecorder is the mock recorder for MockUserAuthRepository.
type MockUserAuthRepositoryMockRecorder struct {
	mock *MockUserAuthRepository
}

// NewMockUserAuthRepository creates a new mock instance.
func NewMockUserAuthRepository(ctrl *gomock.Controller) *MockUserAuthRepository {
	mock := &MockUserAuthRepository{ctrl: ctrl}
	mock.recorder = &MockUserAuthRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserAuthRepository) EXPECT() *MockUserAuthRepositoryMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockUserAuthRepository) CreateUser(user entities.User, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", user, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserAuthRepositoryMockRecorder) CreateUser(user, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserAuthRepository)(nil).CreateUser), user, token)
}

// GetUserByEmail mocks base method.
func (m *MockUserAuthRepository) GetUserByEmail(email string) (entities.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", email)
	ret0, _ := ret[0].(entities.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockUserAuthRepositoryMockRecorder) GetUserByEmail(email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockUserAuthRepository)(nil).GetUserByEmail), email)
}

// GetUserByEmailOrUsername mocks base method.
func (m *MockUserAuthRepository) GetUserByEmailOrUsername(email, username string) (entities.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmailOrUsername", email, username)
	ret0, _ := ret[0].(entities.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmailOrUsername indicates an expected call of GetUserByEmailOrUsername.
func (mr *MockUserAuthRepositoryMockRecorder) GetUserByEmailOrUsername(email, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmailOrUsername", reflect.TypeOf((*MockUserAuthRepository)(nil).GetUserByEmailOrUsername), email, username)
}

// GetUserByRecovery mocks base method.
func (m *MockUserAuthRepository) GetUserByRecovery(userEmail, code string, expiredAt time.Time) (entities.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByRecovery", userEmail, code, expiredAt)
	ret0, _ := ret[0].(entities.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByRecovery indicates an expected call of GetUserByRecovery.
func (mr *MockUserAuthRepositoryMockRecorder) GetUserByRecovery(userEmail, code, expiredAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByRecovery", reflect.TypeOf((*MockUserAuthRepository)(nil).GetUserByRecovery), userEmail, code, expiredAt)
}

// GetUserByUsername mocks base method.
func (m *MockUserAuthRepository) GetUserByUsername(username string) (entities.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByUsername", username)
	ret0, _ := ret[0].(entities.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByUsername indicates an expected call of GetUserByUsername.
func (mr *MockUserAuthRepositoryMockRecorder) GetUserByUsername(username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByUsername", reflect.TypeOf((*MockUserAuthRepository)(nil).GetUserByUsername), username)
}

// GetUserByVerificationCode mocks base method.
func (m *MockUserAuthRepository) GetUserByVerificationCode(code string) (entities.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByVerificationCode", code)
	ret0, _ := ret[0].(entities.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByVerificationCode indicates an expected call of GetUserByVerificationCode.
func (mr *MockUserAuthRepositoryMockRecorder) GetUserByVerificationCode(code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByVerificationCode", reflect.TypeOf((*MockUserAuthRepository)(nil).GetUserByVerificationCode), code)
}

// SetRecoveryCode mocks base method.
func (m *MockUserAuthRepository) SetRecoveryCode(userID entities.HexID, code string, expiresAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRecoveryCode", userID, code, expiresAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetRecoveryCode indicates an expected call of SetRecoveryCode.
func (mr *MockUserAuthRepositoryMockRecorder) SetRecoveryCode(userID, code, expiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRecoveryCode", reflect.TypeOf((*MockUserAuthRepository)(nil).SetRecoveryCode), userID, code, expiresAt)
}

// SetUserVerified mocks base method.
func (m *MockUserAuthRepository) SetUserVerified(userID entities.HexID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUserVerified", userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetUserVerified indicates an expected call of SetUserVerified.
func (mr *MockUserAuthRepositoryMockRecorder) SetUserVerified(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUserVerified", reflect.TypeOf((*MockUserAuthRepository)(nil).SetUserVerified), userID)
}

// UpdatePassword mocks base method.
func (m *MockUserAuthRepository) UpdatePassword(userID entities.HexID, newPassword string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePassword", userID, newPassword)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePassword indicates an expected call of UpdatePassword.
func (mr *MockUserAuthRepositoryMockRecorder) UpdatePassword(userID, newPassword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePassword", reflect.TypeOf((*MockUserAuthRepository)(nil).UpdatePassword), userID, newPassword)
}
