// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/jictyvoo/amigonimo_api/internal/domain/authcore/authserv/requestrecovery (interfaces: Mailer)
//
// Generated by this command:
//
//	mockgen -destination=mailer_mock_test.go -package=requestrecovery github.com/jictyvoo/amigonimo_api/internal/domain/authcore/authserv/requestrecovery Mailer
//

// Package requestrecovery is a generated GoMock package.
package requestrecovery

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMailer is a mock of Mailer interface.
type MockMailer struct {
	ctrl     *gomock.Controller
	recorder *MockMailerMockRecorder
	isgomock struct{}
}

// MockMailerMockRecorder is the mock recorder for MockMailer.
type MockMailerMockRecorder struct {
	mock *MockMailer
}

// NewMockMailer creates a new mock instance.
func NewMockMailer(ctrl *gomock.Controller) *MockMailer {
	mock := &MockMailer{ctrl: ctrl}
	mock.recorder = &MockMailerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMailer) EXPECT() *MockMailerMockRecorder {
	return m.recorder
}

// SendPasswordRecoveryEmail mocks base method.
func (m *MockMailer) SendPasswordRecoveryEmail(email, recoveryCode string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SendPasswordRecoveryEmail", email, recoveryCode)
}

// SendPasswordRecoveryEmail indicates an expected call of SendPasswordRecoveryEmail.
func (mr *MockMailerMockRecorder) SendPasswordRecoveryEmail(email, recoveryCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendPasswordRecoveryEmail", reflect.TypeOf((*MockMailer)(nil).SendPasswordRecoveryEmail), email, recoveryCode)
}
