// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/jictyvoo/amigonimo_api/internal/domain/authcore/authserv/requestrecovery (interfaces: UserRepository)
//
// Generated by this command:
//
//	mockgen -destination=user_repository_mock_test.go -package=requestrecovery github.com/jictyvoo/amigonimo_api/internal/domain/authcore/authserv/requestrecovery UserRepository
//

// Package requestrecovery is a generated GoMock package.
package requestrecovery

import (
	reflect "reflect"
	time "time"

	entities "github.com/jictyvoo/amigonimo_api/internal/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// GetUserByEmail mocks base method.
func (m *MockUserRepository) GetUserByEmail(userEmail string) (entities.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", userEmail)
	ret0, _ := ret[0].(entities.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockUserRepositoryMockRecorder) GetUserByEmail(userEmail any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockUserRepository)(nil).GetUserByEmail), userEmail)
}

// SetRecoveryCode mocks base method.
func (m *MockUserRepository) SetRecoveryCode(userID entities.HexID, code string, expiresAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRecoveryCode", userID, code, expiresAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetRecoveryCode indicates an expected call of SetRecoveryCode.
func (mr *MockUserRepositoryMockRecorder) SetRecoveryCode(userID, code, expiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRecoveryCode", reflect.TypeOf((*MockUserRepository)(nil).SetRecoveryCode), userID, code, expiresAt)
}
