services:
  mariadb:
    image: mariadb:12
    env_file:
      - path: build/local.mariadb.env
        required: true
    environment:
      MARIADB_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    deploy:
      resources:
        limits:
          memory: 500M   # Max memory
        reservations:
          memory: 250M   # Guaranteed minimum
    healthcheck:
      test: [ "CMD-SHELL", "mariadb -h localhost -u$$MARIADB_USER -p$$MARIADB_PASSWORD -e 'SELECT 1;'" ]
      interval: 20s
      timeout: 5s
      retries: 8
      start_period: 35s
