version: "3"

includes:
  main:
    taskfile: ./Taskfile.build.yml
    dir: .
  docker:
    taskfile: ./Taskfile.docker.yml
    dir: .

vars:
  TEST_CMD: "go test ./..."

tasks:
  default:
    desc: Run the default commands
    cmds:
      - task: dev-env:up
      - "cd build/ && task migration:apply"

  dev-env:up:
    desc: Up all development required environment
    cmds:
      - task: docker:stop
      - task: docker:run
        vars:
          OPTIONS: "--wait"
