// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/jictyvoo/amigonimo_api/internal/domain/authcore/authserv/regenerate (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=repository_mock_test.go -package=regenerate github.com/jictyvoo/amigonimo_api/internal/domain/authcore/authserv/regenerate Repository
//

// Package regenerate is a generated GoMock package.
package regenerate

import (
	reflect "reflect"

	entities "github.com/jictyvoo/amigonimo_api/internal/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CheckAuthenticationByRefreshToken mocks base method.
func (m *MockRepository) CheckAuthenticationByRefreshToken(authToken string) (entities.AuthenticationToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckAuthenticationByRefreshToken", authToken)
	ret0, _ := ret[0].(entities.AuthenticationToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckAuthenticationByRefreshToken indicates an expected call of CheckAuthenticationByRefreshToken.
func (mr *MockRepositoryMockRecorder) CheckAuthenticationByRefreshToken(authToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckAuthenticationByRefreshToken", reflect.TypeOf((*MockRepository)(nil).CheckAuthenticationByRefreshToken), authToken)
}

// UpsertAuthToken mocks base method.
func (m *MockRepository) UpsertAuthToken(authentication *entities.AuthenticationToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertAuthToken", authentication)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertAuthToken indicates an expected call of UpsertAuthToken.
func (mr *MockRepositoryMockRecorder) UpsertAuthToken(authentication any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertAuthToken", reflect.TypeOf((*MockRepository)(nil).UpsertAuthToken), authentication)
}
