// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/jictyvoo/amigonimo_api/internal/domain/usecases/drawfriends/getresult (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=repository_mock_test.go -package=getresult github.com/jictyvoo/amigonimo_api/internal/domain/usecases/drawfriends/getresult Repository
//

// Package getresult is a generated GoMock package.
package getresult

import (
	reflect "reflect"

	drawdto "github.com/jictyvoo/amigonimo_api/internal/domain/usecases/drawfriends/drawdto"
	entities "github.com/jictyvoo/amigonimo_api/internal/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetDrawResultForUser mocks base method.
func (m *MockRepository) GetDrawResultForUser(secretFriendID, userID entities.HexID) (drawdto.DrawResultItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDrawResultForUser", secretFriendID, userID)
	ret0, _ := ret[0].(drawdto.DrawResultItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDrawResultForUser indicates an expected call of GetDrawResultForUser.
func (mr *MockRepositoryMockRecorder) GetDrawResultForUser(secretFriendID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDrawResultForUser", reflect.TypeOf((*MockRepository)(nil).GetDrawResultForUser), secretFriendID, userID)
}
