// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/jictyvoo/amigonimo_api/internal/domain/authcore/authserv/checkrecovery (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=repository_mock_test.go -package=checkrecovery github.com/jictyvoo/amigonimo_api/internal/domain/authcore/authserv/checkrecovery Repository
//

// Package checkrecovery is a generated GoMock package.
package checkrecovery

import (
	reflect "reflect"
	time "time"

	entities "github.com/jictyvoo/amigonimo_api/internal/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetUserByRecovery mocks base method.
func (m *MockRepository) GetUserByRecovery(userEmail, code string, expiredAt time.Time) (entities.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByRecovery", userEmail, code, expiredAt)
	ret0, _ := ret[0].(entities.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByRecovery indicates an expected call of GetUserByRecovery.
func (mr *MockRepositoryMockRecorder) GetUserByRecovery(userEmail, code, expiredAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByRecovery", reflect.TypeOf((*MockRepository)(nil).GetUserByRecovery), userEmail, code, expiredAt)
}
