// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package mappers

import (
	entities "github.com/jictyvoo/amigonimo_api/internal/entities"
	dbgen "github.com/jictyvoo/amigonimo_api/internal/infra/repositories/mysqlrepo/internal/dbgen"
)

func ToEntityAuthenticationToken(source dbgen.AuthToken) entities.AuthenticationToken {
	var entitiesAuthenticationToken entities.AuthenticationToken
	entitiesAuthenticationToken.BasicAuthToken = convertBasicAuthToken(source)
	entitiesAuthenticationToken.ID = HexIDFromBytes(source.ID)
	entitiesAuthenticationToken.User = convertTokenUserToEntityUser(source)
	return entitiesAuthenticationToken
}
func convertBasicAuthToken(source dbgen.AuthToken) entities.BasicAuthToken {
	var entitiesBasicAuthToken entities.BasicAuthToken
	entitiesBasicAuthToken.AuthToken = source.Token
	entitiesBasicAuthToken.ExpiresAt = TimeFromNullTime(source.ExpiresAt)
	entitiesBasicAuthToken.RefreshToken = UUIDFromNullString(source.RefreshToken)
	return entitiesBasicAuthToken
}
func convertTokenUserToEntityUser(source dbgen.AuthToken) entities.User {
	var entitiesUser entities.User
	entitiesUser.ID = HexIDFromBytes(source.UserID)
	return entitiesUser
}
