// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package mappers

import (
	entities "github.com/jictyvoo/amigonimo_api/internal/entities"
	dbgen "github.com/jictyvoo/amigonimo_api/internal/infra/repositories/mysqlrepo/internal/dbgen"
)

func ToEntityDeniedUser(source dbgen.GetDenyListByParticipantRow) entities.DeniedUser {
	var entitiesDeniedUser entities.DeniedUser
	entitiesDeniedUser.Timestamp = dbgenGetDenyListByParticipantRowToEntitiesTimestamp(source)
	entitiesDeniedUser.ID = HexIDFromBytes(source.DeniedUserID)
	entitiesDeniedUser.InnerParticipant = dbDenyRowToDeniedParticipant(source)
	return entitiesDeniedUser
}
func dbDenyRowToBasicDeniedUserData(source dbgen.GetDenyListByParticipantRow) entities.UserBasic {
	var entitiesUserBasic entities.UserBasic
	entitiesUserBasic.Username = source.Username
	entitiesUserBasic.Email = source.Email
	return entitiesUserBasic
}
func dbDenyRowToDeniedParticipant(source dbgen.GetDenyListByParticipantRow) entities.Participant {
	var entitiesParticipant entities.Participant
	entitiesParticipant.Timestamp = dbgenGetDenyListByParticipantRowToEntitiesTimestamp(source)
	entitiesParticipant.ID = HexIDFromBytes(source.ID)
	entitiesParticipant.RelatedUser = dbDenyRowToDeniedUser(source)
	entitiesParticipant.JoinedAt = CopyTime(source.CreatedAt)
	return entitiesParticipant
}
func dbDenyRowToDeniedUser(source dbgen.GetDenyListByParticipantRow) entities.User {
	var entitiesUser entities.User
	entitiesUser.UserBasic = dbDenyRowToBasicDeniedUserData(source)
	entitiesUser.ID = HexIDFromBytes(source.DeniedUserID)
	entitiesUser.FullName = source.Fullname
	return entitiesUser
}
func dbgenGetDenyListByParticipantRowToEntitiesTimestamp(source dbgen.GetDenyListByParticipantRow) entities.Timestamp {
	var entitiesTimestamp entities.Timestamp
	entitiesTimestamp.CreatedAt = CopyTime(source.CreatedAt)
	entitiesTimestamp.UpdatedAt = CopyTime(source.UpdatedAt)
	return entitiesTimestamp
}
