// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package mappers

import (
	denylist "github.com/jictyvoo/amigonimo_api/internal/domain/usecases/denylist"
	entities "github.com/jictyvoo/amigonimo_api/internal/entities"
	dbgen "github.com/jictyvoo/amigonimo_api/internal/infra/repositories/mysqlrepo/internal/dbgen"
)

func ToDeniedEntry(source dbgen.GetDenyListByParticipantRow) denylist.DeniedEntry {
	var denylistDeniedEntry denylist.DeniedEntry
	denylistDeniedEntry.Timestamp = dbDenylistToTimestamp(source.Denylist)
	denylistDeniedEntry.ID = HexIDFromBytes(source.Denylist.ID)
	denylistDeniedEntry.DeniedUserID = HexIDFromBytes(source.Denylist.DeniedUserID)
	denylistDeniedEntry.Username = source.Username
	denylistDeniedEntry.Email = source.Email
	denylistDeniedEntry.FullName = source.Fullname
	return denylistDeniedEntry
}
func dbDenylistToTimestamp(source dbgen.Denylist) entities.Timestamp {
	var entitiesTimestamp entities.Timestamp
	entitiesTimestamp.CreatedAt = CopyTime(source.CreatedAt)
	entitiesTimestamp.UpdatedAt = CopyTime(source.UpdatedAt)
	return entitiesTimestamp
}
