// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package mappers

import (
	entities "github.com/jictyvoo/amigonimo_api/internal/entities"
	dbgen "github.com/jictyvoo/amigonimo_api/internal/infra/repositories/mysqlrepo/internal/dbgen"
)

func ToEntityParticipant(source dbgen.Participant) entities.Participant {
	var entitiesParticipant entities.Participant
	entitiesParticipant.Timestamp = dbPartipantTimestampToEntity(source)
	entitiesParticipant.ID = HexIDFromBytes(source.ID)
	entitiesParticipant.RelatedUser = dbPartipantToRelatedUser(source)
	entitiesParticipant.SecretFriendID = HexIDFromBytes(source.SecretFriendID)
	entitiesParticipant.JoinedAt = TimeFromNullTime(source.JoinedAt)
	return entitiesParticipant
}
func dbPartipantTimestampToEntity(source dbgen.Participant) entities.Timestamp {
	var entitiesTimestamp entities.Timestamp
	entitiesTimestamp.CreatedAt = CopyTime(source.CreatedAt)
	entitiesTimestamp.UpdatedAt = CopyTime(source.UpdatedAt)
	return entitiesTimestamp
}
func dbPartipantToRelatedUser(source dbgen.Participant) entities.User {
	var entitiesUser entities.User
	entitiesUser.ID = HexIDFromBytes(source.UserID)
	return entitiesUser
}
