// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package mappers

import (
	entities "github.com/jictyvoo/amigonimo_api/internal/entities"
	dbgen "github.com/jictyvoo/amigonimo_api/internal/infra/repositories/mysqlrepo/internal/dbgen"
)

func ToEntitySecretFriend(source dbgen.SecretFriend) entities.SecretFriend {
	var entitiesSecretFriend entities.SecretFriend
	entitiesSecretFriend.Timestamp = dbSecretFriendTimestampToEntity(source)
	entitiesSecretFriend.ID = HexIDFromBytes(source.ID)
	entitiesSecretFriend.Name = source.Name
	entitiesSecretFriend.Datetime = TimeFromNullTime(source.Datetime)
	entitiesSecretFriend.Location = StringFromNullString(source.Location)
	entitiesSecretFriend.OwnerID = HexIDFromBytes(source.OwnerID)
	entitiesSecretFriend.InviteCode = source.InviteCode
	entitiesSecretFriend.MaxDenyListSize = source.MaxDenyListSize
	entitiesSecretFriend.Status = StatusToEntity(source.Status)
	return entitiesSecretFriend
}
func dbSecretFriendTimestampToEntity(source dbgen.SecretFriend) entities.Timestamp {
	var entitiesTimestamp entities.Timestamp
	entitiesTimestamp.CreatedAt = CopyTime(source.CreatedAt)
	entitiesTimestamp.UpdatedAt = CopyTime(source.UpdatedAt)
	return entitiesTimestamp
}
