// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package mappers

import (
	entities "github.com/jictyvoo/amigonimo_api/internal/entities"
	authvalues "github.com/jictyvoo/amigonimo_api/internal/entities/authvalues"
	dbgen "github.com/jictyvoo/amigonimo_api/internal/infra/repositories/mysqlrepo/internal/dbgen"
)

func ToEntityUser(source dbgen.User) entities.User {
	var entitiesUser entities.User
	entitiesUser.UserBasic = convertUserBasic(source)
	entitiesUser.ID = HexIDFromBytes(source.ID)
	entitiesUser.VerifiedAt = TimeFromNullTime(source.VerifiedAt)
	entitiesUser.RememberToken = StringFromNullString(source.RememberToken)
	return entitiesUser
}
func convertUserBasic(source dbgen.User) authvalues.UserBasic {
	var authvaluesUserBasic authvalues.UserBasic
	authvaluesUserBasic.Username = source.Username
	authvaluesUserBasic.Email = source.Email
	authvaluesUserBasic.Password = source.Password
	return authvaluesUserBasic
}
