// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package mappers

import (
	entities "github.com/jictyvoo/amigonimo_api/internal/entities"
	dbgen "github.com/jictyvoo/amigonimo_api/internal/infra/repositories/mysqlrepo/internal/dbgen"
)

func ToEntityUser(source dbgen.User) entities.User {
	var entitiesUser entities.User
	entitiesUser.UserBasic = convertUserBasic(source)
	entitiesUser.ID = HexIDFromBytes(source.ID)
	entitiesUser.VerifiedAt = TimeFromNullTime(source.VerifiedAt)
	entitiesUser.RememberToken = StringFromNullString(source.RememberToken)
	return entitiesUser
}
func convertUserBasic(source dbgen.User) entities.UserBasic {
	var entitiesUserBasic entities.UserBasic
	entitiesUserBasic.Username = source.Username
	entitiesUserBasic.Email = source.Email
	entitiesUserBasic.Password = source.Password
	return entitiesUserBasic
}
