// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package mappers

import (
	entities "github.com/jictyvoo/amigonimo_api/internal/entities"
	dbgen "github.com/jictyvoo/amigonimo_api/internal/infra/repositories/mysqlrepo/internal/dbgen"
)

func ToEntityWishlistItem(source dbgen.WishlistItem) entities.WishlistItem {
	var entitiesWishlistItem entities.WishlistItem
	entitiesWishlistItem.Timestamp = dbWishlistTimestampToEntity(source)
	entitiesWishlistItem.ID = HexIDFromBytes(source.ID)
	entitiesWishlistItem.Label = source.Label
	entitiesWishlistItem.Comments = StringFromNullString(source.Comments)
	return entitiesWishlistItem
}
func dbWishlistTimestampToEntity(source dbgen.WishlistItem) entities.Timestamp {
	var entitiesTimestamp entities.Timestamp
	entitiesTimestamp.CreatedAt = CopyTime(source.CreatedAt)
	entitiesTimestamp.UpdatedAt = CopyTime(source.UpdatedAt)
	return entitiesTimestamp
}
