// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/jictyvoo/amigonimo_api/internal/domain/usecases/wishlist (interfaces: participantFacadePort,Repository)
//
// Generated by this command:
//
//	mockgen -destination=wishlist_mock_test.go -package=wishlist github.com/jictyvoo/amigonimo_api/internal/domain/usecases/wishlist participantFacadePort,Repository
//

// Package wishlist is a generated GoMock package.
package wishlist

import (
	reflect "reflect"

	entities "github.com/jictyvoo/amigonimo_api/internal/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockparticipantFacadePort is a mock of participantFacadePort interface.
type MockparticipantFacadePort struct {
	ctrl     *gomock.Controller
	recorder *MockparticipantFacadePortMockRecorder
	isgomock struct{}
}

// MockparticipantFacadePortMockRecorder is the mock recorder for MockparticipantFacadePort.
type MockparticipantFacadePortMockRecorder struct {
	mock *MockparticipantFacadePort
}

// NewMockparticipantFacadePort creates a new mock instance.
func NewMockparticipantFacadePort(ctrl *gomock.Controller) *MockparticipantFacadePort {
	mock := &MockparticipantFacadePort{ctrl: ctrl}
	mock.recorder = &MockparticipantFacadePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockparticipantFacadePort) EXPECT() *MockparticipantFacadePortMockRecorder {
	return m.recorder
}

// CheckParticipantInSecretFriend mocks base method.
func (m *MockparticipantFacadePort) CheckParticipantInSecretFriend(sfID, userID entities.HexID) (entities.Participant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckParticipantInSecretFriend", sfID, userID)
	ret0, _ := ret[0].(entities.Participant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckParticipantInSecretFriend indicates an expected call of CheckParticipantInSecretFriend.
func (mr *MockparticipantFacadePortMockRecorder) CheckParticipantInSecretFriend(sfID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckParticipantInSecretFriend", reflect.TypeOf((*MockparticipantFacadePort)(nil).CheckParticipantInSecretFriend), sfID, userID)
}

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// AddWishlistItem mocks base method.
func (m *MockRepository) AddWishlistItem(participant ParticipantRef, wishItem WishlistItem) (WishlistItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddWishlistItem", participant, wishItem)
	ret0, _ := ret[0].(WishlistItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddWishlistItem indicates an expected call of AddWishlistItem.
func (mr *MockRepositoryMockRecorder) AddWishlistItem(participant, wishItem any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddWishlistItem", reflect.TypeOf((*MockRepository)(nil).AddWishlistItem), participant, wishItem)
}

// GetWishlistByParticipant mocks base method.
func (m *MockRepository) GetWishlistByParticipant(participant ParticipantRef) ([]WishlistItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWishlistByParticipant", participant)
	ret0, _ := ret[0].([]WishlistItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWishlistByParticipant indicates an expected call of GetWishlistByParticipant.
func (mr *MockRepositoryMockRecorder) GetWishlistByParticipant(participant any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWishlistByParticipant", reflect.TypeOf((*MockRepository)(nil).GetWishlistByParticipant), participant)
}

// RemoveWishlistItem mocks base method.
func (m *MockRepository) RemoveWishlistItem(itemID entities.HexID, participant ParticipantRef) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveWishlistItem", itemID, participant)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveWishlistItem indicates an expected call of RemoveWishlistItem.
func (mr *MockRepositoryMockRecorder) RemoveWishlistItem(itemID, participant any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveWishlistItem", reflect.TypeOf((*MockRepository)(nil).RemoveWishlistItem), itemID, participant)
}
