// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/jictyvoo/amigonimo_api/internal/domain/authcore/userserv (interfaces: UserEditionRepository)
//
// Generated by this command:
//
//	mockgen -destination=user_edition_repository_mock_test.go -package=userserv github.com/jictyvoo/amigonimo_api/internal/domain/authcore/userserv UserEditionRepository
//

// Package userserv is a generated GoMock package.
package userserv

import (
	reflect "reflect"

	entities "github.com/jictyvoo/amigonimo_api/internal/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockUserEditionRepository is a mock of UserEditionRepository interface.
type MockUserEditionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserEditionRepositoryMockRecorder
	isgomock struct{}
}

// MockUserEditionRepositoryMockRecorder is the mock recorder for MockUserEditionRepository.
type MockUserEditionRepositoryMockRecorder struct {
	mock *MockUserEditionRepository
}

// NewMockUserEditionRepository creates a new mock instance.
func NewMockUserEditionRepository(ctrl *gomock.Controller) *MockUserEditionRepository {
	mock := &MockUserEditionRepository{ctrl: ctrl}
	mock.recorder = &MockUserEditionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserEditionRepository) EXPECT() *MockUserEditionRepositoryMockRecorder {
	return m.recorder
}

// ChangeEmail mocks base method.
func (m *MockUserEditionRepository) ChangeEmail(userID entities.HexID, newEmail string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeEmail", userID, newEmail)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangeEmail indicates an expected call of ChangeEmail.
func (mr *MockUserEditionRepositoryMockRecorder) ChangeEmail(userID, newEmail any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeEmail", reflect.TypeOf((*MockUserEditionRepository)(nil).ChangeEmail), userID, newEmail)
}

// GetUserByAuthCode mocks base method.
func (m *MockUserEditionRepository) GetUserByAuthCode(authToken string) (entities.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByAuthCode", authToken)
	ret0, _ := ret[0].(entities.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByAuthCode indicates an expected call of GetUserByAuthCode.
func (mr *MockUserEditionRepositoryMockRecorder) GetUserByAuthCode(authToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByAuthCode", reflect.TypeOf((*MockUserEditionRepository)(nil).GetUserByAuthCode), authToken)
}

// SetNewVerificationCode mocks base method.
func (m *MockUserEditionRepository) SetNewVerificationCode(userID entities.HexID, code string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetNewVerificationCode", userID, code)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetNewVerificationCode indicates an expected call of SetNewVerificationCode.
func (mr *MockUserEditionRepositoryMockRecorder) SetNewVerificationCode(userID, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetNewVerificationCode", reflect.TypeOf((*MockUserEditionRepository)(nil).SetNewVerificationCode), userID, code)
}

// UpdateUsername mocks base method.
func (m *MockUserEditionRepository) UpdateUsername(userID entities.HexID, username string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUsername", userID, username)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUsername indicates an expected call of UpdateUsername.
func (mr *MockUserEditionRepositoryMockRecorder) UpdateUsername(userID, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUsername", reflect.TypeOf((*MockUserEditionRepository)(nil).UpdateUsername), userID, username)
}
