// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/jictyvoo/amigonimo_api/internal/domain/authcore/authserv/login (interfaces: TokenRepository)
//
// Generated by this command:
//
//	mockgen -destination=token_repository_mock_test.go -package=login github.com/jictyvoo/amigonimo_api/internal/domain/authcore/authserv/login TokenRepository
//

// Package login is a generated GoMock package.
package login

import (
	reflect "reflect"

	entities "github.com/jictyvoo/amigonimo_api/internal/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockTokenRepository is a mock of TokenRepository interface.
type MockTokenRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTokenRepositoryMockRecorder
	isgomock struct{}
}

// MockTokenRepositoryMockRecorder is the mock recorder for MockTokenRepository.
type MockTokenRepositoryMockRecorder struct {
	mock *MockTokenRepository
}

// NewMockTokenRepository creates a new mock instance.
func NewMockTokenRepository(ctrl *gomock.Controller) *MockTokenRepository {
	mock := &MockTokenRepository{ctrl: ctrl}
	mock.recorder = &MockTokenRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenRepository) EXPECT() *MockTokenRepositoryMockRecorder {
	return m.recorder
}

// GetAuthenticationToken mocks base method.
func (m *MockTokenRepository) GetAuthenticationToken(userID entities.HexID) (entities.AuthenticationToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuthenticationToken", userID)
	ret0, _ := ret[0].(entities.AuthenticationToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAuthenticationToken indicates an expected call of GetAuthenticationToken.
func (mr *MockTokenRepositoryMockRecorder) GetAuthenticationToken(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthenticationToken", reflect.TypeOf((*MockTokenRepository)(nil).GetAuthenticationToken), userID)
}

// UpsertAuthToken mocks base method.
func (m *MockTokenRepository) UpsertAuthToken(authentication *entities.AuthenticationToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertAuthToken", authentication)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertAuthToken indicates an expected call of UpsertAuthToken.
func (mr *MockTokenRepositoryMockRecorder) UpsertAuthToken(authentication any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertAuthToken", reflect.TypeOf((*MockTokenRepository)(nil).UpsertAuthToken), authentication)
}
