// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/jictyvoo/amigonimo_api/internal/domain/authcore/authserv/login (interfaces: UserRepository)
//
// Generated by this command:
//
//	mockgen -destination=user_repository_mock_test.go -package=login github.com/jictyvoo/amigonimo_api/internal/domain/authcore/authserv/login UserRepository
//

// Package login is a generated GoMock package.
package login

import (
	reflect "reflect"

	entities "github.com/jictyvoo/amigonimo_api/internal/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// GetUserByEmailOrUsername mocks base method.
func (m *MockUserRepository) GetUserByEmailOrUsername(email, username string) (entities.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmailOrUsername", email, username)
	ret0, _ := ret[0].(entities.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmailOrUsername indicates an expected call of GetUserByEmailOrUsername.
func (mr *MockUserRepositoryMockRecorder) GetUserByEmailOrUsername(email, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmailOrUsername", reflect.TypeOf((*MockUserRepository)(nil).GetUserByEmailOrUsername), email, username)
}
