// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/jictyvoo/amigonimo_api/internal/domain/usecases/denylist (interfaces: ParticipantFacade,SecretFriendFacade)
//
// Generated by this command:
//
//	mockgen -destination=facade_provider_mock_test.go -package=denylist github.com/jictyvoo/amigonimo_api/internal/domain/usecases/denylist ParticipantFacade,SecretFriendFacade
//

// Package denylist is a generated GoMock package.
package denylist

import (
	reflect "reflect"

	entities "github.com/jictyvoo/amigonimo_api/internal/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockParticipantFacade is a mock of ParticipantFacade interface.
type MockParticipantFacade struct {
	ctrl     *gomock.Controller
	recorder *MockParticipantFacadeMockRecorder
	isgomock struct{}
}

// MockParticipantFacadeMockRecorder is the mock recorder for MockParticipantFacade.
type MockParticipantFacadeMockRecorder struct {
	mock *MockParticipantFacade
}

// NewMockParticipantFacade creates a new mock instance.
func NewMockParticipantFacade(ctrl *gomock.Controller) *MockParticipantFacade {
	mock := &MockParticipantFacade{ctrl: ctrl}
	mock.recorder = &MockParticipantFacadeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockParticipantFacade) EXPECT() *MockParticipantFacadeMockRecorder {
	return m.recorder
}

// CheckParticipantInSecretFriend mocks base method.
func (m *MockParticipantFacade) CheckParticipantInSecretFriend(sfID, userID entities.HexID) (entities.Participant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckParticipantInSecretFriend", sfID, userID)
	ret0, _ := ret[0].(entities.Participant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckParticipantInSecretFriend indicates an expected call of CheckParticipantInSecretFriend.
func (mr *MockParticipantFacadeMockRecorder) CheckParticipantInSecretFriend(sfID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckParticipantInSecretFriend", reflect.TypeOf((*MockParticipantFacade)(nil).CheckParticipantInSecretFriend), sfID, userID)
}

// isFacade mocks base method.
func (m *MockParticipantFacade) isFacade() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "isFacade")
}

// isFacade indicates an expected call of isFacade.
func (mr *MockParticipantFacadeMockRecorder) isFacade() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "isFacade", reflect.TypeOf((*MockParticipantFacade)(nil).isFacade))
}

// MockSecretFriendFacade is a mock of SecretFriendFacade interface.
type MockSecretFriendFacade struct {
	ctrl     *gomock.Controller
	recorder *MockSecretFriendFacadeMockRecorder
	isgomock struct{}
}

// MockSecretFriendFacadeMockRecorder is the mock recorder for MockSecretFriendFacade.
type MockSecretFriendFacadeMockRecorder struct {
	mock *MockSecretFriendFacade
}

// NewMockSecretFriendFacade creates a new mock instance.
func NewMockSecretFriendFacade(ctrl *gomock.Controller) *MockSecretFriendFacade {
	mock := &MockSecretFriendFacade{ctrl: ctrl}
	mock.recorder = &MockSecretFriendFacadeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecretFriendFacade) EXPECT() *MockSecretFriendFacadeMockRecorder {
	return m.recorder
}

// GetSecretFriendByID mocks base method.
func (m *MockSecretFriendFacade) GetSecretFriendByID(id entities.HexID) (entities.SecretFriend, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecretFriendByID", id)
	ret0, _ := ret[0].(entities.SecretFriend)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecretFriendByID indicates an expected call of GetSecretFriendByID.
func (mr *MockSecretFriendFacadeMockRecorder) GetSecretFriendByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecretFriendByID", reflect.TypeOf((*MockSecretFriendFacade)(nil).GetSecretFriendByID), id)
}

// isFacade mocks base method.
func (m *MockSecretFriendFacade) isFacade() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "isFacade")
}

// isFacade indicates an expected call of isFacade.
func (mr *MockSecretFriendFacadeMockRecorder) isFacade() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "isFacade", reflect.TypeOf((*MockSecretFriendFacade)(nil).isFacade))
}
