// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/jictyvoo/amigonimo_api/internal/domain/usecases/denylist (interfaces: participantFacadePort,secretFriendFacadePort)
//
// Generated by this command:
//
//	mockgen -destination=facade_provider_mock_test.go -package=denylist github.com/jictyvoo/amigonimo_api/internal/domain/usecases/denylist participantFacadePort,secretFriendFacadePort
//

// Package denylist is a generated GoMock package.
package denylist

import (
	reflect "reflect"

	entities "github.com/jictyvoo/amigonimo_api/internal/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockparticipantFacadePort is a mock of participantFacadePort interface.
type MockparticipantFacadePort struct {
	ctrl     *gomock.Controller
	recorder *MockparticipantFacadePortMockRecorder
	isgomock struct{}
}

// MockparticipantFacadePortMockRecorder is the mock recorder for MockparticipantFacadePort.
type MockparticipantFacadePortMockRecorder struct {
	mock *MockparticipantFacadePort
}

// NewMockparticipantFacadePort creates a new mock instance.
func NewMockparticipantFacadePort(ctrl *gomock.Controller) *MockparticipantFacadePort {
	mock := &MockparticipantFacadePort{ctrl: ctrl}
	mock.recorder = &MockparticipantFacadePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockparticipantFacadePort) EXPECT() *MockparticipantFacadePortMockRecorder {
	return m.recorder
}

// CheckParticipantInSecretFriend mocks base method.
func (m *MockparticipantFacadePort) CheckParticipantInSecretFriend(sfID, userID entities.HexID) (entities.Participant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckParticipantInSecretFriend", sfID, userID)
	ret0, _ := ret[0].(entities.Participant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckParticipantInSecretFriend indicates an expected call of CheckParticipantInSecretFriend.
func (mr *MockparticipantFacadePortMockRecorder) CheckParticipantInSecretFriend(sfID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckParticipantInSecretFriend", reflect.TypeOf((*MockparticipantFacadePort)(nil).CheckParticipantInSecretFriend), sfID, userID)
}

// MocksecretFriendFacadePort is a mock of secretFriendFacadePort interface.
type MocksecretFriendFacadePort struct {
	ctrl     *gomock.Controller
	recorder *MocksecretFriendFacadePortMockRecorder
	isgomock struct{}
}

// MocksecretFriendFacadePortMockRecorder is the mock recorder for MocksecretFriendFacadePort.
type MocksecretFriendFacadePortMockRecorder struct {
	mock *MocksecretFriendFacadePort
}

// NewMocksecretFriendFacadePort creates a new mock instance.
func NewMocksecretFriendFacadePort(ctrl *gomock.Controller) *MocksecretFriendFacadePort {
	mock := &MocksecretFriendFacadePort{ctrl: ctrl}
	mock.recorder = &MocksecretFriendFacadePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksecretFriendFacadePort) EXPECT() *MocksecretFriendFacadePortMockRecorder {
	return m.recorder
}

// GetSecretFriendByID mocks base method.
func (m *MocksecretFriendFacadePort) GetSecretFriendByID(id entities.HexID) (entities.SecretFriend, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecretFriendByID", id)
	ret0, _ := ret[0].(entities.SecretFriend)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecretFriendByID indicates an expected call of GetSecretFriendByID.
func (mr *MocksecretFriendFacadePortMockRecorder) GetSecretFriendByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecretFriendByID", reflect.TypeOf((*MocksecretFriendFacadePort)(nil).GetSecretFriendByID), id)
}
