// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/jictyvoo/amigonimo_api/internal/domain/usecases/denylist (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=repository_mock_test.go -package=denylist github.com/jictyvoo/amigonimo_api/internal/domain/usecases/denylist Repository
//

// Package denylist is a generated GoMock package.
package denylist

import (
	reflect "reflect"

	entities "github.com/jictyvoo/amigonimo_api/internal/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// AddDenyListEntry mocks base method.
func (m *MockRepository) AddDenyListEntry(participant ParticipantRef, deniedUserID entities.HexID) (entities.DeniedUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddDenyListEntry", participant, deniedUserID)
	ret0, _ := ret[0].(entities.DeniedUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddDenyListEntry indicates an expected call of AddDenyListEntry.
func (mr *MockRepositoryMockRecorder) AddDenyListEntry(participant, deniedUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddDenyListEntry", reflect.TypeOf((*MockRepository)(nil).AddDenyListEntry), participant, deniedUserID)
}

// GetDenyListByParticipant mocks base method.
func (m *MockRepository) GetDenyListByParticipant(participant ParticipantRef) ([]entities.DeniedUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDenyListByParticipant", participant)
	ret0, _ := ret[0].([]entities.DeniedUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDenyListByParticipant indicates an expected call of GetDenyListByParticipant.
func (mr *MockRepositoryMockRecorder) GetDenyListByParticipant(participant any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDenyListByParticipant", reflect.TypeOf((*MockRepository)(nil).GetDenyListByParticipant), participant)
}

// RemoveDenyListEntry mocks base method.
func (m *MockRepository) RemoveDenyListEntry(participant ParticipantRef, deniedUserID entities.HexID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveDenyListEntry", participant, deniedUserID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveDenyListEntry indicates an expected call of RemoveDenyListEntry.
func (mr *MockRepositoryMockRecorder) RemoveDenyListEntry(participant, deniedUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveDenyListEntry", reflect.TypeOf((*MockRepository)(nil).RemoveDenyListEntry), participant, deniedUserID)
}
