// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/jictyvoo/amigonimo_api/internal/domain/usecases/denylist (interfaces: SecretFriendFacade)
//
// Generated by this command:
//
//	mockgen -destination=secret_friend_facade_mock_test.go -package=denylist github.com/jictyvoo/amigonimo_api/internal/domain/usecases/denylist SecretFriendFacade
//

// Package denylist is a generated GoMock package.
package denylist

import (
	reflect "reflect"

	entities "github.com/jictyvoo/amigonimo_api/internal/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockSecretFriendFacade is a mock of SecretFriendFacade interface.
type MockSecretFriendFacade struct {
	ctrl     *gomock.Controller
	recorder *MockSecretFriendFacadeMockRecorder
	isgomock struct{}
}

// MockSecretFriendFacadeMockRecorder is the mock recorder for MockSecretFriendFacade.
type MockSecretFriendFacadeMockRecorder struct {
	mock *MockSecretFriendFacade
}

// NewMockSecretFriendFacade creates a new mock instance.
func NewMockSecretFriendFacade(ctrl *gomock.Controller) *MockSecretFriendFacade {
	mock := &MockSecretFriendFacade{ctrl: ctrl}
	mock.recorder = &MockSecretFriendFacadeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecretFriendFacade) EXPECT() *MockSecretFriendFacadeMockRecorder {
	return m.recorder
}

// GetSecretFriendByID mocks base method.
func (m *MockSecretFriendFacade) GetSecretFriendByID(id entities.HexID) (entities.SecretFriend, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecretFriendByID", id)
	ret0, _ := ret[0].(entities.SecretFriend)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecretFriendByID indicates an expected call of GetSecretFriendByID.
func (mr *MockSecretFriendFacadeMockRecorder) GetSecretFriendByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecretFriendByID", reflect.TypeOf((*MockSecretFriendFacade)(nil).GetSecretFriendByID), id)
}

// isFacade mocks base method.
func (m *MockSecretFriendFacade) isFacade() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "isFacade")
}

// isFacade indicates an expected call of isFacade.
func (mr *MockSecretFriendFacadeMockRecorder) isFacade() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "isFacade", reflect.TypeOf((*MockSecretFriendFacade)(nil).isFacade))
}
