// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/jictyvoo/amigonimo_api/internal/domain/usecases/drawfriends (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=repository_mock_test.go -package=drawfriends github.com/jictyvoo/amigonimo_api/internal/domain/usecases/drawfriends Repository
//

// Package drawfriends is a generated GoMock package.
package drawfriends

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	entities "github.com/jictyvoo/amigonimo_api/internal/entities"
	dbrock "github.com/jictyvoo/amigonimo_api/pkg/dbrock"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// BeginTx mocks base method.
func (m *MockRepository) BeginTx(ctx context.Context, txOpts *sql.TxOptions) (dbrock.OnFinishFunc, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTx", ctx, txOpts)
	ret0, _ := ret[0].(dbrock.OnFinishFunc)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginTx indicates an expected call of BeginTx.
func (mr *MockRepositoryMockRecorder) BeginTx(ctx, txOpts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTx", reflect.TypeOf((*MockRepository)(nil).BeginTx), ctx, txOpts)
}

// GetDrawResultForUser mocks base method.
func (m *MockRepository) GetDrawResultForUser(secretFriendID, userID entities.HexID) (entities.DrawResultItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDrawResultForUser", secretFriendID, userID)
	ret0, _ := ret[0].(entities.DrawResultItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDrawResultForUser indicates an expected call of GetDrawResultForUser.
func (mr *MockRepositoryMockRecorder) GetDrawResultForUser(secretFriendID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDrawResultForUser", reflect.TypeOf((*MockRepository)(nil).GetDrawResultForUser), secretFriendID, userID)
}

// GetSecretFriendByID mocks base method.
func (m *MockRepository) GetSecretFriendByID(id entities.HexID) (entities.SecretFriend, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecretFriendByID", id)
	ret0, _ := ret[0].(entities.SecretFriend)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecretFriendByID indicates an expected call of GetSecretFriendByID.
func (mr *MockRepositoryMockRecorder) GetSecretFriendByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecretFriendByID", reflect.TypeOf((*MockRepository)(nil).GetSecretFriendByID), id)
}

// ListParticipants mocks base method.
func (m *MockRepository) ListParticipants(ctx context.Context, secretFriendID entities.HexID) ([]entities.Participant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListParticipants", ctx, secretFriendID)
	ret0, _ := ret[0].([]entities.Participant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListParticipants indicates an expected call of ListParticipants.
func (mr *MockRepositoryMockRecorder) ListParticipants(ctx, secretFriendID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListParticipants", reflect.TypeOf((*MockRepository)(nil).ListParticipants), ctx, secretFriendID)
}

// SaveDrawResults mocks base method.
func (m *MockRepository) SaveDrawResults(secretFriendID entities.HexID, results []entities.DrawResultItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveDrawResults", secretFriendID, results)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveDrawResults indicates an expected call of SaveDrawResults.
func (mr *MockRepositoryMockRecorder) SaveDrawResults(secretFriendID, results any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveDrawResults", reflect.TypeOf((*MockRepository)(nil).SaveDrawResults), secretFriendID, results)
}

// UpdateSecretFriend mocks base method.
func (m *MockRepository) UpdateSecretFriend(sf *entities.SecretFriend) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSecretFriend", sf)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSecretFriend indicates an expected call of UpdateSecretFriend.
func (mr *MockRepositoryMockRecorder) UpdateSecretFriend(sf any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSecretFriend", reflect.TypeOf((*MockRepository)(nil).UpdateSecretFriend), sf)
}
