// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/jictyvoo/amigonimo_api/internal/domain/authcore/userserv/changeemail (interfaces: Mailer)
//
// Generated by this command:
//
//	mockgen -destination=mailer_mock_test.go -package=changeemail github.com/jictyvoo/amigonimo_api/internal/domain/authcore/userserv/changeemail Mailer
//

// Package changeemail is a generated GoMock package.
package changeemail

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMailer is a mock of Mailer interface.
type MockMailer struct {
	ctrl     *gomock.Controller
	recorder *MockMailerMockRecorder
	isgomock struct{}
}

// MockMailerMockRecorder is the mock recorder for MockMailer.
type MockMailerMockRecorder struct {
	mock *MockMailer
}

// NewMockMailer creates a new mock instance.
func NewMockMailer(ctrl *gomock.Controller) *MockMailer {
	mock := &MockMailer{ctrl: ctrl}
	mock.recorder = &MockMailerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMailer) EXPECT() *MockMailerMockRecorder {
	return m.recorder
}

// SendActivationEmail mocks base method.
func (m *MockMailer) SendActivationEmail(email, verificationToken string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SendActivationEmail", email, verificationToken)
}

// SendActivationEmail indicates an expected call of SendActivationEmail.
func (mr *MockMailerMockRecorder) SendActivationEmail(email, verificationToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendActivationEmail", reflect.TypeOf((*MockMailer)(nil).SendActivationEmail), email, verificationToken)
}
