// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/jictyvoo/amigonimo_api/internal/domain/authcore/userserv/changeemail (interfaces: UserRepository,Repository,Mailer)
//
// Generated by this command:
//
//	mockgen -destination=repository_mock_test.go -package=changeemail github.com/jictyvoo/amigonimo_api/internal/domain/authcore/userserv/changeemail UserRepository,Repository,Mailer
//

// Package changeemail is a generated GoMock package.
package changeemail

import (
	reflect "reflect"

	entities "github.com/jictyvoo/amigonimo_api/internal/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// GetUserByEmail mocks base method.
func (m *MockUserRepository) GetUserByEmail(email string) (entities.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", email)
	ret0, _ := ret[0].(entities.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockUserRepositoryMockRecorder) GetUserByEmail(email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockUserRepository)(nil).GetUserByEmail), email)
}

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// ChangeEmail mocks base method.
func (m *MockRepository) ChangeEmail(userID entities.HexID, newEmail string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeEmail", userID, newEmail)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangeEmail indicates an expected call of ChangeEmail.
func (mr *MockRepositoryMockRecorder) ChangeEmail(userID, newEmail any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeEmail", reflect.TypeOf((*MockRepository)(nil).ChangeEmail), userID, newEmail)
}

// GetUserByAuthCode mocks base method.
func (m *MockRepository) GetUserByAuthCode(authToken string) (entities.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByAuthCode", authToken)
	ret0, _ := ret[0].(entities.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByAuthCode indicates an expected call of GetUserByAuthCode.
func (mr *MockRepositoryMockRecorder) GetUserByAuthCode(authToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByAuthCode", reflect.TypeOf((*MockRepository)(nil).GetUserByAuthCode), authToken)
}

// SetNewVerificationCode mocks base method.
func (m *MockRepository) SetNewVerificationCode(userID entities.HexID, code string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetNewVerificationCode", userID, code)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetNewVerificationCode indicates an expected call of SetNewVerificationCode.
func (mr *MockRepositoryMockRecorder) SetNewVerificationCode(userID, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetNewVerificationCode", reflect.TypeOf((*MockRepository)(nil).SetNewVerificationCode), userID, code)
}

// MockMailer is a mock of Mailer interface.
type MockMailer struct {
	ctrl     *gomock.Controller
	recorder *MockMailerMockRecorder
	isgomock struct{}
}

// MockMailerMockRecorder is the mock recorder for MockMailer.
type MockMailerMockRecorder struct {
	mock *MockMailer
}

// NewMockMailer creates a new mock instance.
func NewMockMailer(ctrl *gomock.Controller) *MockMailer {
	mock := &MockMailer{ctrl: ctrl}
	mock.recorder = &MockMailerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMailer) EXPECT() *MockMailerMockRecorder {
	return m.recorder
}

// SendActivationEmail mocks base method.
func (m *MockMailer) SendActivationEmail(email, verificationToken string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SendActivationEmail", email, verificationToken)
}

// SendActivationEmail indicates an expected call of SendActivationEmail.
func (mr *MockMailerMockRecorder) SendActivationEmail(email, verificationToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendActivationEmail", reflect.TypeOf((*MockMailer)(nil).SendActivationEmail), email, verificationToken)
}
