// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/jictyvoo/amigonimo_api/internal/domain/authcore/userserv/changeemail (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=repository_mock_test.go -package=changeemail github.com/jictyvoo/amigonimo_api/internal/domain/authcore/userserv/changeemail Repository
//

// Package changeemail is a generated GoMock package.
package changeemail

import (
	reflect "reflect"

	entities "github.com/jictyvoo/amigonimo_api/internal/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// ChangeEmail mocks base method.
func (m *MockRepository) ChangeEmail(userID entities.HexID, newEmail string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeEmail", userID, newEmail)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangeEmail indicates an expected call of ChangeEmail.
func (mr *MockRepositoryMockRecorder) ChangeEmail(userID, newEmail any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeEmail", reflect.TypeOf((*MockRepository)(nil).ChangeEmail), userID, newEmail)
}

// GetUserByAuthCode mocks base method.
func (m *MockRepository) GetUserByAuthCode(authToken string) (entities.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByAuthCode", authToken)
	ret0, _ := ret[0].(entities.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByAuthCode indicates an expected call of GetUserByAuthCode.
func (mr *MockRepositoryMockRecorder) GetUserByAuthCode(authToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByAuthCode", reflect.TypeOf((*MockRepository)(nil).GetUserByAuthCode), authToken)
}

// SetNewVerificationCode mocks base method.
func (m *MockRepository) SetNewVerificationCode(userID entities.HexID, code string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetNewVerificationCode", userID, code)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetNewVerificationCode indicates an expected call of SetNewVerificationCode.
func (mr *MockRepositoryMockRecorder) SetNewVerificationCode(userID, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetNewVerificationCode", reflect.TypeOf((*MockRepository)(nil).SetNewVerificationCode), userID, code)
}
