// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth_token.sql

package dbgen

import (
	"context"
	"database/sql"
)

const CheckAuthenticationByRefreshToken = `-- name: CheckAuthenticationByRefreshToken :one
SELECT id, created_at, updated_at, token, refresh_token, expires_at, user_id
FROM auth_tokens
WHERE refresh_token = ?
`

func (q *Queries) CheckAuthenticationByRefreshToken(ctx context.Context, refreshToken sql.NullString) (AuthToken, error) {
	row := q.db.QueryRowContext(ctx, CheckAuthenticationByRefreshToken, refreshToken)
	var i AuthToken
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Token,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.UserID,
	)
	return i, err
}

const GetAuthenticationToken = `-- name: GetAuthenticationToken :one
SELECT id, created_at, updated_at, token, refresh_token, expires_at, user_id
FROM auth_tokens
WHERE user_id = ?
`

func (q *Queries) GetAuthenticationToken(ctx context.Context, userID []byte) (AuthToken, error) {
	row := q.db.QueryRowContext(ctx, GetAuthenticationToken, userID)
	var i AuthToken
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Token,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.UserID,
	)
	return i, err
}

const GetUserByAuthToken = `-- name: GetUserByAuthToken :one
SELECT u.id, u.created_at, u.updated_at, u.fullname, u.email, u.username, u.password, u.verified_at, u.remember_token, u.verification_code, u.recovery_code, u.recovery_code_expires_at
FROM users u
         INNER JOIN auth_tokens at ON u.id = at.user_id
WHERE at.token = ?
`

func (q *Queries) GetUserByAuthToken(ctx context.Context, token string) (User, error) {
	row := q.db.QueryRowContext(ctx, GetUserByAuthToken, token)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Fullname,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.VerifiedAt,
		&i.RememberToken,
		&i.VerificationCode,
		&i.RecoveryCode,
		&i.RecoveryCodeExpiresAt,
	)
	return i, err
}

const UpsertAuthToken = `-- name: UpsertAuthToken :execresult
INSERT INTO auth_tokens (id, user_id, token, refresh_token, expires_at, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, NOW(), NOW())
ON DUPLICATE KEY UPDATE token         = VALUES(token),
                        refresh_token = VALUES(refresh_token),
                        expires_at    = VALUES(expires_at),
                        updated_at    = NOW()
`

type UpsertAuthTokenParams struct {
	ID           []byte         `db:"id"`
	UserID       []byte         `db:"user_id"`
	Token        string         `db:"token"`
	RefreshToken sql.NullString `db:"refresh_token"`
	ExpiresAt    sql.NullTime   `db:"expires_at"`
}

func (q *Queries) UpsertAuthToken(ctx context.Context, arg UpsertAuthTokenParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, UpsertAuthToken,
		arg.ID,
		arg.UserID,
		arg.Token,
		arg.RefreshToken,
		arg.ExpiresAt,
	)
}
