// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: denylists.sql

package dbgen

import (
	"context"
	"database/sql"
)

const AddDenyListEntry = `-- name: AddDenyListEntry :execresult
INSERT INTO denylists (id, participant_id, denied_user_id, created_at, updated_at)
VALUES (?,
        COALESCE(
                ?,
                (SELECT p.id
                 FROM participants p
                 WHERE p.user_id = ?
                   AND p.secret_friend_id = ?
                 LIMIT 1)
        ),
        ?, NOW(), NOW())
`

type AddDenyListEntryParams struct {
	ID             []byte      `db:"id"`
	ParticipantID  interface{} `db:"participant_id"`
	UserID         []byte      `db:"user_id"`
	SecretFriendID []byte      `db:"secret_friend_id"`
	DeniedUserID   []byte      `db:"denied_user_id"`
}

func (q *Queries) AddDenyListEntry(ctx context.Context, arg AddDenyListEntryParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, AddDenyListEntry,
		arg.ID,
		arg.ParticipantID,
		arg.UserID,
		arg.SecretFriendID,
		arg.DeniedUserID,
	)
}

const GetDenyListByParticipant = `-- name: GetDenyListByParticipant :many
SELECT d.id, d.created_at, d.updated_at, d.participant_id, d.denied_user_id, COALESCE(up.fullname, '') AS fullname, u.email, u.username, u.id AS user_id
FROM denylists d
         JOIN users u ON d.denied_user_id = u.id
         LEFT JOIN user_profiles up ON up.user_id = u.id
WHERE d.participant_id = COALESCE(
        ?,
        (SELECT p.id
         FROM participants p
         WHERE p.user_id = ?
           AND p.secret_friend_id = ?
         LIMIT 1)
                         )
`

type GetDenyListByParticipantParams struct {
	ParticipantID  []byte `db:"participant_id"`
	UserID         []byte `db:"user_id"`
	SecretFriendID []byte `db:"secret_friend_id"`
}

type GetDenyListByParticipantRow struct {
	Denylist Denylist `db:"denylist"`
	Fullname string   `db:"fullname"`
	Email    string   `db:"email"`
	Username string   `db:"username"`
	UserID   []byte   `db:"user_id"`
}

func (q *Queries) GetDenyListByParticipant(ctx context.Context, arg GetDenyListByParticipantParams) ([]GetDenyListByParticipantRow, error) {
	rows, err := q.db.QueryContext(ctx, GetDenyListByParticipant, arg.ParticipantID, arg.UserID, arg.SecretFriendID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDenyListByParticipantRow{}
	for rows.Next() {
		var i GetDenyListByParticipantRow
		if err := rows.Scan(
			&i.Denylist.ID,
			&i.Denylist.CreatedAt,
			&i.Denylist.UpdatedAt,
			&i.Denylist.ParticipantID,
			&i.Denylist.DeniedUserID,
			&i.Fullname,
			&i.Email,
			&i.Username,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const RemoveDenyListEntry = `-- name: RemoveDenyListEntry :exec
DELETE
FROM denylists
WHERE participant_id = COALESCE(
        ?,
        (SELECT p.id
         FROM participants p
         WHERE p.user_id = ?
           AND p.secret_friend_id = ?
         LIMIT 1)
                       )
  AND denied_user_id = ?
`

type RemoveDenyListEntryParams struct {
	ParticipantID  []byte `db:"participant_id"`
	UserID         []byte `db:"user_id"`
	SecretFriendID []byte `db:"secret_friend_id"`
	DeniedUserID   []byte `db:"denied_user_id"`
}

func (q *Queries) RemoveDenyListEntry(ctx context.Context, arg RemoveDenyListEntryParams) error {
	_, err := q.db.ExecContext(ctx, RemoveDenyListEntry,
		arg.ParticipantID,
		arg.UserID,
		arg.SecretFriendID,
		arg.DeniedUserID,
	)
	return err
}
