// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: participants.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const AddParticipant = `-- name: AddParticipant :execresult
INSERT INTO participants (id, secret_friend_id, user_id, joined_at, created_at, updated_at)
VALUES (?, ?, ?, NOW(), NOW(), NOW())
`

type AddParticipantParams struct {
	ID             []byte `db:"id"`
	SecretFriendID []byte `db:"secret_friend_id"`
	UserID         []byte `db:"user_id"`
}

func (q *Queries) AddParticipant(ctx context.Context, arg AddParticipantParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, AddParticipant, arg.ID, arg.SecretFriendID, arg.UserID)
}

const GetParticipantByID = `-- name: GetParticipantByID :one
SELECT id, created_at, updated_at, joined_at, secret_friend_id, user_id
FROM participants
WHERE id = ?
`

func (q *Queries) GetParticipantByID(ctx context.Context, id []byte) (Participant, error) {
	row := q.db.QueryRowContext(ctx, GetParticipantByID, id)
	var i Participant
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.JoinedAt,
		&i.SecretFriendID,
		&i.UserID,
	)
	return i, err
}

const GetParticipantBySFAndUser = `-- name: GetParticipantBySFAndUser :one
SELECT id, created_at, updated_at, joined_at, secret_friend_id, user_id
FROM participants
WHERE secret_friend_id = ?
  AND user_id = ?
`

type GetParticipantBySFAndUserParams struct {
	SecretFriendID []byte `db:"secret_friend_id"`
	UserID         []byte `db:"user_id"`
}

func (q *Queries) GetParticipantBySFAndUser(ctx context.Context, arg GetParticipantBySFAndUserParams) (Participant, error) {
	row := q.db.QueryRowContext(ctx, GetParticipantBySFAndUser, arg.SecretFriendID, arg.UserID)
	var i Participant
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.JoinedAt,
		&i.SecretFriendID,
		&i.UserID,
	)
	return i, err
}

const ListParticipantsBySecretFriend = `-- name: ListParticipantsBySecretFriend :many
SELECT p.id, p.created_at, p.updated_at, p.joined_at, p.secret_friend_id, p.user_id, u.fullname, u.email, u.username
FROM participants p
         JOIN users u ON p.user_id = u.id
WHERE p.secret_friend_id = ?
`

type ListParticipantsBySecretFriendRow struct {
	ID             []byte       `db:"id"`
	CreatedAt      time.Time    `db:"created_at"`
	UpdatedAt      time.Time    `db:"updated_at"`
	JoinedAt       sql.NullTime `db:"joined_at"`
	SecretFriendID []byte       `db:"secret_friend_id"`
	UserID         []byte       `db:"user_id"`
	Fullname       string       `db:"fullname"`
	Email          string       `db:"email"`
	Username       string       `db:"username"`
}

func (q *Queries) ListParticipantsBySecretFriend(ctx context.Context, secretFriendID []byte) ([]ListParticipantsBySecretFriendRow, error) {
	rows, err := q.db.QueryContext(ctx, ListParticipantsBySecretFriend, secretFriendID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListParticipantsBySecretFriendRow{}
	for rows.Next() {
		var i ListParticipantsBySecretFriendRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.JoinedAt,
			&i.SecretFriendID,
			&i.UserID,
			&i.Fullname,
			&i.Email,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
