// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: secret_friend.sql

package dbgen

import (
	"context"
	"database/sql"
)

const CreateSecretFriend = `-- name: CreateSecretFriend :execresult
INSERT INTO secret_friends (id, name, datetime, location, invite_code, status, owner_id, max_deny_list_size, created_at,
                            updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, NOW(), NOW())
`

type CreateSecretFriendParams struct {
	ID              []byte         `db:"id"`
	Name            string         `db:"name"`
	Datetime        sql.NullTime   `db:"datetime"`
	Location        sql.NullString `db:"location"`
	InviteCode      string         `db:"invite_code"`
	Status          string         `db:"status"`
	OwnerID         []byte         `db:"owner_id"`
	MaxDenyListSize uint8          `db:"max_deny_list_size"`
}

func (q *Queries) CreateSecretFriend(ctx context.Context, arg CreateSecretFriendParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, CreateSecretFriend,
		arg.ID,
		arg.Name,
		arg.Datetime,
		arg.Location,
		arg.InviteCode,
		arg.Status,
		arg.OwnerID,
		arg.MaxDenyListSize,
	)
}

const GetSecretFriendByID = `-- name: GetSecretFriendByID :one
SELECT id, created_at, updated_at, name, datetime, location, max_deny_list_size, invite_code, invite_link, status, owner_id
FROM secret_friends
WHERE id = ?
`

func (q *Queries) GetSecretFriendByID(ctx context.Context, id []byte) (SecretFriend, error) {
	row := q.db.QueryRowContext(ctx, GetSecretFriendByID, id)
	var i SecretFriend
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Datetime,
		&i.Location,
		&i.MaxDenyListSize,
		&i.InviteCode,
		&i.InviteLink,
		&i.Status,
		&i.OwnerID,
	)
	return i, err
}

const GetSecretFriendByInviteCode = `-- name: GetSecretFriendByInviteCode :one
SELECT id, created_at, updated_at, name, datetime, location, max_deny_list_size, invite_code, invite_link, status, owner_id
FROM secret_friends
WHERE invite_code = ?
`

func (q *Queries) GetSecretFriendByInviteCode(ctx context.Context, inviteCode string) (SecretFriend, error) {
	row := q.db.QueryRowContext(ctx, GetSecretFriendByInviteCode, inviteCode)
	var i SecretFriend
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Datetime,
		&i.Location,
		&i.MaxDenyListSize,
		&i.InviteCode,
		&i.InviteLink,
		&i.Status,
		&i.OwnerID,
	)
	return i, err
}

const ListSecretFriends = `-- name: ListSecretFriends :many
SELECT id, created_at, updated_at, name, datetime, location, max_deny_list_size, invite_code, invite_link, status, owner_id
FROM secret_friends
WHERE owner_id = ?
   OR id IN (SELECT secret_friend_id FROM participants p WHERE p.user_id = ?)
ORDER BY created_at DESC
`

type ListSecretFriendsParams struct {
	OwnerID []byte `db:"owner_id"`
	UserID  []byte `db:"user_id"`
}

func (q *Queries) ListSecretFriends(ctx context.Context, arg ListSecretFriendsParams) ([]SecretFriend, error) {
	rows, err := q.db.QueryContext(ctx, ListSecretFriends, arg.OwnerID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SecretFriend{}
	for rows.Next() {
		var i SecretFriend
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Datetime,
			&i.Location,
			&i.MaxDenyListSize,
			&i.InviteCode,
			&i.InviteLink,
			&i.Status,
			&i.OwnerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateSecretFriend = `-- name: UpdateSecretFriend :exec
UPDATE secret_friends
SET name       = ?,
    datetime   = ?,
    location   = ?,
    status     = ?,
    updated_at = NOW()
WHERE id = ?
`

type UpdateSecretFriendParams struct {
	Name     string         `db:"name"`
	Datetime sql.NullTime   `db:"datetime"`
	Location sql.NullString `db:"location"`
	Status   string         `db:"status"`
	ID       []byte         `db:"id"`
}

func (q *Queries) UpdateSecretFriend(ctx context.Context, arg UpdateSecretFriendParams) error {
	_, err := q.db.ExecContext(ctx, UpdateSecretFriend,
		arg.Name,
		arg.Datetime,
		arg.Location,
		arg.Status,
		arg.ID,
	)
	return err
}
