// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_profiles.sql

package dbgen

import (
	"context"
	"database/sql"
)

const CreateUserProfile = `-- name: CreateUserProfile :execresult
INSERT INTO user_profiles (id, user_id, fullname, nickname, image_link, birthday, address, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, NOW(), NOW())
`

type CreateUserProfileParams struct {
	ID        []byte         `db:"id"`
	UserID    []byte         `db:"user_id"`
	Fullname  sql.NullString `db:"fullname"`
	Nickname  sql.NullString `db:"nickname"`
	ImageLink sql.NullString `db:"image_link"`
	Birthday  sql.NullTime   `db:"birthday"`
	Address   sql.NullString `db:"address"`
}

func (q *Queries) CreateUserProfile(ctx context.Context, arg CreateUserProfileParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, CreateUserProfile,
		arg.ID,
		arg.UserID,
		arg.Fullname,
		arg.Nickname,
		arg.ImageLink,
		arg.Birthday,
		arg.Address,
	)
}

const GetUserProfileByUserID = `-- name: GetUserProfileByUserID :one
SELECT id, created_at, updated_at, fullname, nickname, image_link, birthday, address, user_id
FROM user_profiles
WHERE user_id = ?
`

func (q *Queries) GetUserProfileByUserID(ctx context.Context, userID []byte) (UserProfile, error) {
	row := q.db.QueryRowContext(ctx, GetUserProfileByUserID, userID)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Fullname,
		&i.Nickname,
		&i.ImageLink,
		&i.Birthday,
		&i.Address,
		&i.UserID,
	)
	return i, err
}

const UpsertUserProfile = `-- name: UpsertUserProfile :execresult
INSERT INTO user_profiles (id, user_id, fullname, nickname, image_link, birthday, address, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, NOW(), NOW())
ON DUPLICATE KEY UPDATE fullname   = VALUES(fullname),
                        nickname   = VALUES(nickname),
                        image_link = VALUES(image_link),
                        birthday   = VALUES(birthday),
                        address    = VALUES(address),
                        updated_at = NOW()
`

type UpsertUserProfileParams struct {
	ID        []byte         `db:"id"`
	UserID    []byte         `db:"user_id"`
	Fullname  sql.NullString `db:"fullname"`
	Nickname  sql.NullString `db:"nickname"`
	ImageLink sql.NullString `db:"image_link"`
	Birthday  sql.NullTime   `db:"birthday"`
	Address   sql.NullString `db:"address"`
}

func (q *Queries) UpsertUserProfile(ctx context.Context, arg UpsertUserProfileParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, UpsertUserProfile,
		arg.ID,
		arg.UserID,
		arg.Fullname,
		arg.Nickname,
		arg.ImageLink,
		arg.Birthday,
		arg.Address,
	)
}
