// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const CreateUser = `-- name: CreateUser :execresult
INSERT INTO users (id, fullname, email, created_at, updated_at)
VALUES (?, ?, ?, NOW(), NOW())
`

type CreateUserParams struct {
	ID       []byte `db:"id"`
	Fullname string `db:"fullname"`
	Email    string `db:"email"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, CreateUser, arg.ID, arg.Fullname, arg.Email)
}

const GetUserByEmail = `-- name: GetUserByEmail :one
SELECT id, fullname, email, created_at, updated_at
FROM users
WHERE email = ?
`

type GetUserByEmailRow struct {
	ID        []byte    `db:"id"`
	Fullname  string    `db:"fullname"`
	Email     string    `db:"email"`
	CreatedAt time.Time `db:"created_at"`
	UpdatedAt time.Time `db:"updated_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, GetUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Fullname,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetUserByID = `-- name: GetUserByID :one
SELECT id, fullname, email, created_at, updated_at
FROM users
WHERE id = ?
`

type GetUserByIDRow struct {
	ID        []byte    `db:"id"`
	Fullname  string    `db:"fullname"`
	Email     string    `db:"email"`
	CreatedAt time.Time `db:"created_at"`
	UpdatedAt time.Time `db:"updated_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id []byte) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, GetUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Fullname,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
