// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wishlist_items.sql

package dbgen

import (
	"context"
	"database/sql"
)

const AddWishlistItem = `-- name: AddWishlistItem :execresult
INSERT INTO wishlist_items (id, participant_id, label, comments, created_at, updated_at)
VALUES (?,
        COALESCE(
                ?,
                (SELECT id
                 FROM participants
                 WHERE user_id = ?
                   AND secret_friend_id = ?
                 LIMIT 1)
        ),
        ?, ?, NOW(), NOW())
`

type AddWishlistItemParams struct {
	ID             []byte         `db:"id"`
	ParticipantID  interface{}    `db:"participant_id"`
	UserID         []byte         `db:"user_id"`
	SecretFriendID []byte         `db:"secret_friend_id"`
	Label          string         `db:"label"`
	Comments       sql.NullString `db:"comments"`
}

func (q *Queries) AddWishlistItem(ctx context.Context, arg AddWishlistItemParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, AddWishlistItem,
		arg.ID,
		arg.ParticipantID,
		arg.UserID,
		arg.SecretFriendID,
		arg.Label,
		arg.Comments,
	)
}

const GetWishlistByParticipant = `-- name: GetWishlistByParticipant :many
SELECT id, created_at, updated_at, label, comments, participant_id
FROM wishlist_items
WHERE wishlist_items.participant_id = COALESCE(
        ?,
        (SELECT id
         FROM participants
         WHERE user_id = ?
           AND secret_friend_id = ?
         LIMIT 1)
                                      )
ORDER BY created_at DESC
`

type GetWishlistByParticipantParams struct {
	ParticipantID  []byte `db:"participant_id"`
	UserID         []byte `db:"user_id"`
	SecretFriendID []byte `db:"secret_friend_id"`
}

func (q *Queries) GetWishlistByParticipant(ctx context.Context, arg GetWishlistByParticipantParams) ([]WishlistItem, error) {
	rows, err := q.db.QueryContext(ctx, GetWishlistByParticipant, arg.ParticipantID, arg.UserID, arg.SecretFriendID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WishlistItem{}
	for rows.Next() {
		var i WishlistItem
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Label,
			&i.Comments,
			&i.ParticipantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const RemoveWishlistItem = `-- name: RemoveWishlistItem :exec
DELETE
FROM wishlist_items
WHERE wishlist_items.id = ?
  AND wishlist_items.participant_id = COALESCE(
        ?,
        (SELECT id
         FROM participants
         WHERE user_id = ?
           AND secret_friend_id = ?
         LIMIT 1)
                                      )
`

type RemoveWishlistItemParams struct {
	ID             []byte `db:"id"`
	ParticipantID  []byte `db:"participant_id"`
	UserID         []byte `db:"user_id"`
	SecretFriendID []byte `db:"secret_friend_id"`
}

func (q *Queries) RemoveWishlistItem(ctx context.Context, arg RemoveWishlistItemParams) error {
	_, err := q.db.ExecContext(ctx, RemoveWishlistItem,
		arg.ID,
		arg.ParticipantID,
		arg.UserID,
		arg.SecretFriendID,
	)
	return err
}
