// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/jictyvoo/amigonimo_api/internal/domain/usecases/secretfriend (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=repository_mock_test.go -package=secretfriend github.com/jictyvoo/amigonimo_api/internal/domain/usecases/secretfriend Repository
//

// Package secretfriend is a generated GoMock package.
package secretfriend

import (
	reflect "reflect"

	entities "github.com/jictyvoo/amigonimo_api/internal/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreateSecretFriend mocks base method.
func (m *MockRepository) CreateSecretFriend(sf *entities.SecretFriend) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSecretFriend", sf)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSecretFriend indicates an expected call of CreateSecretFriend.
func (mr *MockRepositoryMockRecorder) CreateSecretFriend(sf any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSecretFriend", reflect.TypeOf((*MockRepository)(nil).CreateSecretFriend), sf)
}

// GetSecretFriendByID mocks base method.
func (m *MockRepository) GetSecretFriendByID(id entities.HexID) (entities.SecretFriend, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecretFriendByID", id)
	ret0, _ := ret[0].(entities.SecretFriend)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecretFriendByID indicates an expected call of GetSecretFriendByID.
func (mr *MockRepositoryMockRecorder) GetSecretFriendByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecretFriendByID", reflect.TypeOf((*MockRepository)(nil).GetSecretFriendByID), id)
}

// GetSecretFriendByInviteCode mocks base method.
func (m *MockRepository) GetSecretFriendByInviteCode(code string) (entities.SecretFriend, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecretFriendByInviteCode", code)
	ret0, _ := ret[0].(entities.SecretFriend)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecretFriendByInviteCode indicates an expected call of GetSecretFriendByInviteCode.
func (mr *MockRepositoryMockRecorder) GetSecretFriendByInviteCode(code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecretFriendByInviteCode", reflect.TypeOf((*MockRepository)(nil).GetSecretFriendByInviteCode), code)
}

// ListSecretFriends mocks base method.
func (m *MockRepository) ListSecretFriends(userID entities.HexID) ([]entities.SecretFriend, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSecretFriends", userID)
	ret0, _ := ret[0].([]entities.SecretFriend)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSecretFriends indicates an expected call of ListSecretFriends.
func (mr *MockRepositoryMockRecorder) ListSecretFriends(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSecretFriends", reflect.TypeOf((*MockRepository)(nil).ListSecretFriends), userID)
}

// UpdateSecretFriend mocks base method.
func (m *MockRepository) UpdateSecretFriend(sf *entities.SecretFriend) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSecretFriend", sf)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSecretFriend indicates an expected call of UpdateSecretFriend.
func (mr *MockRepositoryMockRecorder) UpdateSecretFriend(sf any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSecretFriend", reflect.TypeOf((*MockRepository)(nil).UpdateSecretFriend), sf)
}
