// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/jictyvoo/amigonimo_api/internal/domain/usecases/participant (interfaces: SecretFriendFacade,Repository)
//
// Generated by this command:
//
//	mockgen -destination=participant_mock_test.go -package=participant github.com/jictyvoo/amigonimo_api/internal/domain/usecases/participant SecretFriendFacade,Repository
//

// Package participant is a generated GoMock package.
package participant

import (
	reflect "reflect"

	entities "github.com/jictyvoo/amigonimo_api/internal/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockSecretFriendFacade is a mock of SecretFriendFacade interface.
type MockSecretFriendFacade struct {
	ctrl     *gomock.Controller
	recorder *MockSecretFriendFacadeMockRecorder
	isgomock struct{}
}

// MockSecretFriendFacadeMockRecorder is the mock recorder for MockSecretFriendFacade.
type MockSecretFriendFacadeMockRecorder struct {
	mock *MockSecretFriendFacade
}

// NewMockSecretFriendFacade creates a new mock instance.
func NewMockSecretFriendFacade(ctrl *gomock.Controller) *MockSecretFriendFacade {
	mock := &MockSecretFriendFacade{ctrl: ctrl}
	mock.recorder = &MockSecretFriendFacadeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecretFriendFacade) EXPECT() *MockSecretFriendFacadeMockRecorder {
	return m.recorder
}

// CheckUserIsOwner mocks base method.
func (m *MockSecretFriendFacade) CheckUserIsOwner(sfID entities.HexID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckUserIsOwner", sfID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckUserIsOwner indicates an expected call of CheckUserIsOwner.
func (mr *MockSecretFriendFacadeMockRecorder) CheckUserIsOwner(sfID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckUserIsOwner", reflect.TypeOf((*MockSecretFriendFacade)(nil).CheckUserIsOwner), sfID)
}

// GetSecretFriendByID mocks base method.
func (m *MockSecretFriendFacade) GetSecretFriendByID(id entities.HexID) (entities.SecretFriend, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecretFriendByID", id)
	ret0, _ := ret[0].(entities.SecretFriend)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecretFriendByID indicates an expected call of GetSecretFriendByID.
func (mr *MockSecretFriendFacadeMockRecorder) GetSecretFriendByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecretFriendByID", reflect.TypeOf((*MockSecretFriendFacade)(nil).GetSecretFriendByID), id)
}

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// AddParticipant mocks base method.
func (m *MockRepository) AddParticipant(sfID, userID entities.HexID) (entities.Participant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddParticipant", sfID, userID)
	ret0, _ := ret[0].(entities.Participant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddParticipant indicates an expected call of AddParticipant.
func (mr *MockRepositoryMockRecorder) AddParticipant(sfID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddParticipant", reflect.TypeOf((*MockRepository)(nil).AddParticipant), sfID, userID)
}

// GetParticipant mocks base method.
func (m *MockRepository) GetParticipant(sfID, userID entities.HexID) (entities.Participant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetParticipant", sfID, userID)
	ret0, _ := ret[0].(entities.Participant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetParticipant indicates an expected call of GetParticipant.
func (mr *MockRepositoryMockRecorder) GetParticipant(sfID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetParticipant", reflect.TypeOf((*MockRepository)(nil).GetParticipant), sfID, userID)
}

// ListParticipants mocks base method.
func (m *MockRepository) ListParticipants(sfID entities.HexID) ([]entities.Participant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListParticipants", sfID)
	ret0, _ := ret[0].([]entities.Participant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListParticipants indicates an expected call of ListParticipants.
func (mr *MockRepositoryMockRecorder) ListParticipants(sfID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListParticipants", reflect.TypeOf((*MockRepository)(nil).ListParticipants), sfID)
}

// RemoveParticipant mocks base method.
func (m *MockRepository) RemoveParticipant(sfID, userID entities.HexID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveParticipant", sfID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveParticipant indicates an expected call of RemoveParticipant.
func (mr *MockRepositoryMockRecorder) RemoveParticipant(sfID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveParticipant", reflect.TypeOf((*MockRepository)(nil).RemoveParticipant), sfID, userID)
}

// SetParticipantReady mocks base method.
func (m *MockRepository) SetParticipantReady(sfID, userID entities.HexID, isReady bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetParticipantReady", sfID, userID, isReady)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetParticipantReady indicates an expected call of SetParticipantReady.
func (mr *MockRepositoryMockRecorder) SetParticipantReady(sfID, userID, isReady any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetParticipantReady", reflect.TypeOf((*MockRepository)(nil).SetParticipantReady), sfID, userID, isReady)
}
